# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iRun' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iRun

  target 'iRunTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
pod 'OneSignal', '~> 1.13.3'
